# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value


services:
    app.activity:
          class: AppBundle\Service\ActivityService
          arguments: ["@doctrine.orm.entity_manager", "@app.current_user_data_service"]
    app.result:
          class: AppBundle\Service\ResultService
          arguments: ["@doctrine.orm.entity_manager", "@app.current_user_data_service"]
    app.lesson_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Lesson
    app.lesson_service:
        class: AppBundle\Service\LessonService
        arguments:
            - "@app.lesson_repository"
            - "@app.time_service"
    app.time_service:
        class: AppBundle\Service\TimeService
    app.student_info:
        class: AppBundle\Service\StudentInfoService
        arguments: [ "@doctrine.orm.entity_manager", "@app.current_user_data_service" ]
    my_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        #facebook: facebook_id, this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@fos_user.user_manager",{ google: google_id}]
    twig.extensions:
        class: AppBundle\Twig\TwigExtensions
        tags:
            - { name: twig.extension }
        arguments:
            - '@app.current_user_data_service'
    app.current_user_data_service:
        class: AppBundle\Service\CurrentUserDataService
        arguments:
            - '@security.token_storage'
    app.result_hidden_type:
        class: AppBundle\Form\ResultHiddenType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
          - { name: form.type, alias: app_result_hidden_type }
    app.result_type:
        class: AppBundle\Form\ResultType
        arguments: [ "@doctrine.orm.entity_manager", "@app.current_user_data_service" ]
        tags:
          - { name: form.type, alias: app_result_type }
    app.top_result_type:
        class: AppBundle\Form\TopResultType
        arguments: [ "@doctrine.orm.entity_manager", "@app.current_user_data_service" ]
        tags:
          - { name: form.type, alias: app_top_result_type }
    app.form.registration_type:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.profile_picture_uploader_service:
        class: AppBundle\Service\FileUploadService
        arguments: ['%profile_images_directory%']

